FROM mariadb

# COPY mariabackup /etc/init.d/mariabackup_cron
#
# RUN update-rc.d mariabackup_cron defaults
# RUN update-rc.d mariabackup_cron enable
#
# RUN apt update && apt install -y vim cron

ENV MARIADB_ROOT_PASSWORD 1
ENV MARIADB_DATABASE test

# CMD mariadbd
