#!/bin/sh
### BEGIN INIT INFO
# Provides:          mariabackup_cron
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start MariaDB backup service at boot
# Description:       Backup MariaDB periodically using mariabackup
### END INIT INFO

cron="%M"
prev=$(date "+${cron}")
pid_file="/var/run/mariabackup_cron.pid"

if [ ! -d /backup ]; then
    mkdir -p /backup
fi

case "$1" in
    start)
        echo "Starting mariabackup_cron..."
        if [ -f "$pid_file" ]; then
            echo "Service is already running!"
            exit 1
        fi

        # Chạy backup trong nền
        while true; do
            now=$(date "+${cron}")
            if [ "$now" != "$prev" ]; then
                backdir=$(date "+$(hostname)_%Y_%m_%d_%H_%M")

                mariadb-backup --backup --target-dir="/backup/${backdir}" --user=root --password=1 >/dev/null 2>&1
                mariadb-backup --prepare --target-dir="/backup/${backdir}" >/dev/null 2>&1

                tar -cJf "/backup_mount/${backdir}.txz" "/backup/${backdir}" >/dev/null 2>&1
                prev="$now"
            fi
            sleep 30
        done &
        echo $! > "$pid_file"
        ;;

    stop)
        echo "Stopping mariabackup_cron..."
        if [ ! -f "$pid_file" ]; then
            echo "Service is not running!"
            exit 1
        fi

        # Dừng tiến trình đang chạy
        kill "$(cat "$pid_file")"
        rm -f "$pid_file"
        echo "Service stopped."
        ;;

    status)
        if [ -f "$pid_file" ];then
            echo "Service is running with PID $(cat "$pid_file")."
        else
            echo "Service is not running."
        fi
        ;;

    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac

